# Site settings
name: Q!Chollos
description: "La web de chollos y ofertas temáticas.<br>¿Qué te interesa comprar?"
url: "http://qchollos.com"

front_img: yes
front_img_path: "/imgs/background.jpg"

# Build settings
markdown: kramdown
permalink: pretty

#Data Page Generator
page_gen-dirs: false

page_gen:
- data: 'channels'
  template: 'channel'
  dir: 'ofertas'
  name: 'section_slug'
  title: name
# name_expr: [a Ruby expression to generate the filename (alternative to name)]
# title_expr: [a Ruby expression to generate the filename (alternative to title)]
# extension: [extension used to generate the filename]
# filter: [property to filter data records by]
# filter_condition: [a Ruby expression to filter data]
